ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP5()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_864 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_902 = -((MDL_CDBIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_903 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_904 = (MDL_CDWIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_905 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_916 = (MDL_CDBIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_917 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_918 = (MDL_CDWIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_919 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_944 = -((MDL_CLEDQIM*MDL_YE*MDL_YS)/MDL_LAMBDASMEFT__EXP__2)
      GC_945 = (MDL_CLEDQIM*MDL_YE*MDL_YS)/MDL_LAMBDASMEFT__EXP__2
      GC_949 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YE*MDL_YS)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_953 = -((MDL_CLEDQIM*MDL_YM*MDL_YS)/MDL_LAMBDASMEFT__EXP__2)
      GC_954 = (MDL_CLEDQIM*MDL_YM*MDL_YS)/MDL_LAMBDASMEFT__EXP__2
      GC_958 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YM*MDL_YS)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1288 = -((MDL_CTH*MDL_CUBIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1289 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1296 = -((MDL_CTH*MDL_CUWIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1298 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1309 = (MDL_CUBIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1310 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1311 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1312 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1355 = -((MDL_CLEQU1IM*MDL_YE*MDL_YUP)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1356 = (MDL_CLEQU1IM*MDL_YE*MDL_YUP)/MDL_LAMBDASMEFT__EXP__2
      END
