ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP3()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_575 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_576 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_577 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_636 = -((MDL_CDBIM*MDL_CTH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_637 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_638 = (MDL_CDWIM*MDL_CTH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_639 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_650 = (MDL_CDBIM*MDL_STH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_651 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_652 = (MDL_CDWIM*MDL_STH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_653 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_706 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_707 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_708 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_709 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_718 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_719 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_720 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_721 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_737 = -((MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_738 = (MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      GC_742 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_746 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_747 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_748 = (MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      END
