ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_U35_alphaScheme_UFO'
     $ //'-qqH_SM_limit'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_135 = ', GC_135
      WRITE(*,2) 'GC_195 = ', GC_195
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_261 = ', GC_261
      WRITE(*,2) 'GC_285 = ', GC_285
      WRITE(*,2) 'GC_602 = ', GC_602
      WRITE(*,2) 'GC_678 = ', GC_678
      WRITE(*,2) 'GC_773 = ', GC_773
